### PR TITLE
Pull Request for Ticket #19499

### PR DESCRIPTION
**Pull request by kiere**
Here are the updates for the mysql2 gem.

### CODE REVIEW

**Comment by 7hunderbird** [comment]
Hello Kiere and Lazygray,

I'm going to look at this pull request now and I'll let you know what I think.

Thanks,

Tyler (filmprog)

**Comment by intjonathan** [comment]
It'd sure be nice to have this merged, we switched to mysql2 last night and have to take backups by hand now. :(

**Comment by 7hunderbird** [comment]
niralisse,

I will prioritize this as my next patch to merge.

Thanks for the bump!

Tyler

**Comment by 7hunderbird** [comment]
Please install 0.5.15 or above for this change.

**Pull request merged**
