### PR TITLE
add RVM support

### PR DESCRIPTION
**Pull request by mpapis**
1. change `bundler` task to not use `--deployment` when using RVM
2. add task to create RVM alias and wrappers for `application` so it's easy to use it in scripting / cron

to activate RVM support:

``` ruby
set :rvm_type, :system
set :rvm_ruby_string, "1.9.3@#{application}"
set :rvm_require_role, :rvm
require "rvm/capistrano"
```

use `:app` for `:rvm_require_role` if all `:app` servers should use RVM

cron support:

``` bash
application="my-app-name-from-deploy.rb"
PATH=/usr/local/rvm/wrappers/${application}
```

conditional scripts:

``` bash
application="my-app-name-from-deploy.rb"
rvm_path=/usr/local/rvm
if [[ -s "$rvm_path/environments/${application}" ]]
then PATH="$rvm_path/wrappers/${application}:$PATH"
fi
```

this is work in progress:
- `gem install rvm-capistrano -v ">=1.3.0.rc11"`
- https://github.com/wayneeseguin/rvm-capistrano/blob/feature/readme_for_1.3.0/README.md

### CODE REVIEW

**Comment by 7hunderbird** [comment]
Wow, this will be a great addition to eycap.  Thank you Michal!

**Comment by mpapis** [comment]
NOTE: currently capistrano output with `parallel` is not that clean, I have opened a pull request to improve it https://github.com/capistrano/capistrano/pull/383

**Comment by 7hunderbird** [comment]
Added this doc page to the wiki => https://github.com/engineyard/eycap/wiki/RVM

**Comment by 7hunderbird** [comment]
I've emailed someone I know in the capistrano team to see if we can expedite that capistrano pull request.

**Comment by mpapis** [comment]
sounds great, thank you!

**Pull request merged**
